### PR TITLE
Fix a couple of typos

### PR DESCRIPTION
**Pull request by parndt**

### CODE REVIEW

**Comment by parndt** [comment]
Let me know if I should edit this to target another branch other than master 😄

**Comment by flash-gordon** [comment]
it should go to master first and _then_ to release branches, I'll cherry-pick. We're in the process of automating things

**Comment by parndt** [comment]
👍 thanks!

**Comment by parndt** [comment]
Before I forget - I noticed the "Edit on GitHub" link on docsite will result in PRs against the particular release, not master, which I guess could make sense if it's a version specific doc change 🤷‍♂ hard to know what to do there.

**Comment by solnic** [comment]
@parndt starting from *today* we have the ability to specify into which release branches a given PR should be merged into, so this is finally a solved problem.

**Comment by parndt** [comment]
👏 well done!

**Pull request merged**
