### PR TITLE
[WIP] Add YARD comments

### PR DESCRIPTION
**Pull request by radanskoric**
This is very much a WIP.

I was reading the code to get an understanding of this little gem and I noticed the total lack of comments so I just thought I might as well try and write them while I'm getting the understanding of the code. 

So I have two questions:

1. Is this something that you would like to see added or was there some reason that YARD was skipped? If the answer is positive I'll add it to the rest of the gem as well and finish the PR.

2. Can you please comment on the style and if it matches what you'd like to see? It's standard YARD so I guess it should be fine but it can't hurt to check. :)

I'd also very much appreciate feedback on the correctness of what I wrote.

### CODE REVIEW

**Comment by flash-gordon** [comment]
Hey, @radanskoric! The only reason why I didn't add comments is that it was on my todo list :) We added examples on the site, we also have 100% coverage so I postponed it for a while. I really appreciate your help with that, I'll check the PR tomorrow.

**Comment by radanskoric** [comment]
@flash-gordon, no problem, I'm happy to contribute. I like the general approach taken by dry-rb and I was going over the gems. Monads caught my eye because I have recently been thinking about using the concept in ruby to see if I can make some code cleaner so I decided to just go through the source. To be honest, writing the docs has also helped me get a clear understanding. :)

I've now finished adding YARD to the whole gem. Please don't hold back on the review comment, I'm happy to improve it.

**Comment by flash-gordon** [comment]
@radanskoric I'm glad you find it intriguing :) I like how expressiveness of Ruby allows to get familiar with monads, the gem has zero private or protected methods. This is a good start for digging deeper, down to origins. A lot of dry-* stuff is based on approaches well-known in functional programming. Understanding them will let you utilize dry gems more efficiently, and, I believe, become a better developer overall. Given you know dry-monads, you might be interested in how it is used in [dry-transaction](http://dry-rb.org/gems/dry-transaction/) and see this [great talk](http://fsharpforfunandprofit.com/rop/).

Thank you very much for your work! ❤️

**Comment by radanskoric** [comment]
Yeah, I saw Railway talk before, great talk. I've got a degree in mathematical engineering so the math behind monads was clear but I didn't have a clear picture of their practical application until I saw the railway analogy, great stuff.

Thank, I'll definitely check out dry-transactions when I'll have time.

**Pull request merged**
