### PR TITLE
Ports "traverse" for Either over from Haskell.

### PR DESCRIPTION
**Pull request by damncabbage**
Used to flip/invert an enumerable of Either values, eg.

```
> traverse [ Right(1), Right(2) ]
=> Right([1,2])
```
```
> traverse [ Right(1), Left(2), Left(3) ]
=> Left(2)
```

... with an optional fmap to perform on each Right, eg.
```
> traverse([ Right(1), Right(2) ]) {|v| v * 2}
=> Right([2, 4])
```

This is a sketch of a PR; I'm not particularly happy with my coding style, I don't know where it should really go (it's Right-biased but I'm not sure how to fit it in there), I don't know whether it should support weird enumerables (see the spec/), and I don't know if you'd want this. 😅 

Please let me know either way if you'd want this, and I'll add it for Maybe (and Try...?) as well.

### CODE REVIEW

**Comment by damncabbage** [comment]
Context for this is that I was coming up with an example for an FP Ruby talk this weekend; I reached for `sequence` (which is just `traverse(list) { |x| x }`, using this example).

```ruby
Either.traverse([user, org, post]).bind do |(u,o,p)|
   rec_org = DB.create_org o
   DB.create_user u, for: rec_ord.id
   # ... etc.
end
```

**Comment by flash-gordon** [comment]
@damncabbage this looks good to me! I'll have a thorough look tomorrow, there is not need to add `traverse` for `Maybe` at the moment, I'm planning to add the `List` monad which will probably generalize this for at least `Either` and `Maybe`. I'm going to catch up with `List` this week and push a new version

**Comment by flash-gordon** [comment]
OK, I will merge it now and will play with my `List` implementation. If everything is fine, I'll change your behavior to return `Right(List ?)` instead of `Right(Array ?)` before releasing the gem

**Comment by damncabbage** [comment]
Thanks; looking forward to it. (Am on holidays at the moment; please pardon the sporadic communication from my end.)

**Pull request merged**
