### PR TITLE
Marshalling

### PR DESCRIPTION
**Pull request by rocknruby**
Developed together with @dhamidi to provide marshalling functionality for `Dry::Monads`.

### CODE REVIEW

**Comment by rocknruby** [comment]
Is not ready to be a proper PR right now

**Comment by flash-gordon** [comment]
hey, @rocknruby 

Marshaling is actually implemented by ruby via converting a ruby object to a string encoded with some binary format:
```ruby
pry(main)> Marshal.dump(Dry::Monads::Some(1))
=> "\x04\bo:\x1DDry::Monads::Maybe::Some\x06:\v@valuei\x06"
```
Ruby has unmarchaling out of the box:
```ruby
pry(main)> Marshal.load(Marshal.dump(Dry::Monads::Some(1)))
=> Some(1)
``` 
Please, do not confuse it with serialization to JSON (look at [this SO question](http://stackoverflow.com/questions/770474/what-is-the-difference-between-serialization-and-marshaling) for details).
This means your specs are passing even if you remove your `to_json` methods.

Frankly speaking, json serialization/deserialization is not dry-m concern after all. Implementing `to_json` methods requires you to add it everywhere, even to the code you don't own. Given that JSON is a widely spread format, this can be not a big issue, but every new format will require adding such custom methods to all classes which is obviously not a scalable approach (see [Expression problem](https://en.wikipedia.org/wiki/Expression_problem) for details).

This problem can and should be avoided in a library, which performs serialization, by providing a proper API, that allows you to set _your_ rules for serialization of _any_ datatype you want.

**Comment by rocknruby** [comment]
@flash-gordon thanks for spending time on this topic. I made it in a rush and had this for a long time on my todo. You are absolutely right, I mixed up the marshaling and JSON serialization topics. 

Anyway, I fixed the spec so that it makes sense why I created the PR. 
I agree the dry-m is maybe not the right place for providing this for the community. 
As an example to JSON serialize a time instance you can `require 'json/add/time'` (see http://ruby-doc.org/stdlib-2.3.0/libdoc/json/rdoc/Time.html ) also look at the spec. So what I would love is something similar. If you agree we can talk about the code. Whats your opinion?

**Comment by rocknruby** [comment]
@flash-gordon I cant reopen the PR after rebasing so the source can be find https://github.com/rocknruby/dry-monads/tree/marshalling

**Comment by flash-gordon** [comment]
ah, thank you for pointing that, I've never looked how this is implemented for core classes. Given that it is done in ruby's standard lib, we can stick with something similar.
Let's have the same structure under lib dir, like this: `dry-monads/lib/json/add/dry/monads/maybe.rb`. Then, in this maybe.rb you can put your `maybe` extension. It will be loaded as soon as you run `require 'json/add/dry/monads/maybe'`

**Pull request closed without merging**
