### PR TITLE
Add Dry::Monads::Try

### PR DESCRIPTION
**Pull request by ttdonovan**
This is mostly what I am personally interested in using. Hopefully it has a place within the `dry-monads` gem. I'm not entirely certain if the `fmap` method is correct for `Dry::Monads::Try::Success` - it passes specs but maybe there is a better way of implementing that method without the extra proc.

### CODE REVIEW

**Comment by timriley** [comment]
Thanks @ttdonovan. I'd love to hear how you'd expect to be using `Try` in realistic scenarios. Swallowing all kinds of exceptions seems a little dangerous to me...

**Comment by ttdonovan** [comment]
@timriley I like to use result monads is service class. The service class itself may chain a bunch of operations together (remote HTTP call, db save, ect) and is responsible for exception messaging, but it's up to the caller to determine how to handle the result. In this case I would like the service class to return a `Dry::Monads::Try`. I've used this gem in the past  https://gitlab.com/zachdaniel/result-monad but would love get this kind of support in the dry-ruby ecosystem.

* http://www.codethatgrows.com/lessons-learned-from-rust-the-result-monad
* https://gitlab.com/zachdaniel/result-monad

Let me know if you need a more detailed example - unfortunately right now most of the code where I'm using `Capture` from `result-monad` is private, but I could maybe put together a fake example if it help demonstrate my use case.

**Comment by timriley** [comment]
Thanks for the explanation! This seems like a pretty reasonable thing to have. I'll wait now for any other people's thoughts before we think about merging.

In the meantime, what are your thoughts about whether `Try.lift` just returning an `Either` instead of a specific `Try` subclass (`Success` or `Failure`)? The only difference seems that the `Success#bind` and `Success#fmap` do the exception rescuing automatically. Is this actually desirable? Or would we prefer to have our users explicitly use `Try { }` whenever they want to rescue from exceptions?

**Comment by ttdonovan** [comment]
@timriley It's a bit unclear to me how the `Try.lift` would know if the call was successful or not using an `Either` without the use of `Success#bind`. Maybe I'm missing something in your question. The implementation was mostly influenced by `Kleisli::Try`.

https://github.com/txus/kleisli/blob/master/lib/kleisli/try.rb

I could be convinced that dry-rb users would have to explicitly use `Try { }` when needing to rescue from exceptions if it's believed to be best practice from the dry community. In that case would the `Try.lift` change to the following?

```
def self.lift(f)
  Dry::Monads::Right(f.call)
rescue => e
  Dry::Monads::Left(e)
end
```

Example if I had three methods calls `#get_http_response`, `#parse_json`, and `#save_to_db`. It might look like the following?

```
Try { get_http_response } >> -> (response) { Try { parse_json(response) } >> -> (obj) { Try { save_to_db(obj) } } }
```

**Comment by timriley** [comment]
@ttdonovan Sorry if I was unclear! Anyway, you captured my thoughts perfectly in this:

```ruby
def self.lift(f)
  Dry::Monads::Right(f.call)
rescue => e
  Dry::Monads::Left(e)
end
```

That's exactly what I was thinking.

Now, as for whether this is a better or easier-to-recommend practice, that's a much broader question, and I'd welcome some input here. 

In my head, I really like this explicitness of your example:

```ruby
Try { get_http_response } >> -> (response) { Try { parse_json(response) } >> -> (obj) { Try { save_to_db(obj) } } }
```

In this code, it's very clear which particular actions you care about rescuing exceptions from. And in this case, it's all of them, because they're all potentially fail-able due to conditions outside of your control.

The reason I thought that making the `Try { }` a required explicit call is because if I were to mix in another step into this chain, one which was entirely within my own app's control, I wouldn't want exceptions to be swallowed up due to programming errors or other things that I should be fixing – in these cases I'd rather be notified about them so I could just correct the bug. What do you think?

**Comment by ttdonovan** [comment]
OK I think that all makes sense. If I get a chance later I'll try to make
the changes else feel free to make the edits yourself.

**Comment by ttdonovan** [comment]
@timriley I've gone ahead and made the changes that we had discussed. Usage would be something like this.

```
> Dry::Monads::Try.lift(-> { 10 / 1 }).fmap { |x| x }.or(Dry::Monads::Right(-1)).fmap { |y| y + 2 }
=> Right(12)

> Dry::Monads::Try.lift(-> { 10 / 0 }).fmap { |x| x }.or(Dry::Monads::Right(-1)).fmap { |y| y + 2 }
 => Right(1)
```

**Comment by timriley** [comment]
You're fast, @ttdonovan! I'll leave this here for the our dry-european friends to check out when they get a chance.

**Comment by ttdonovan** [comment]
@timriley I've made another change to the `Try { }`. Below demonstrates the thought behind the use case. This should be my last change until I receive further feedback. If you have an alternative point of view on how this should be written I am open to suggestions.

```
class Service
  extend Dry::Monads::Try::Mixin

  def self.call
    # code I have limited control over
    try = Try { 10 / 0 }
    (block_given?) ? yield(try) : try
  end
end

res = Service.call
puts "SUCCESS" if res.success?
res.exception if res.failure? # bubble up the exception

Service.call do |res|
  if res.success?
    puts "SUCCESS"
  else
    res.exception # bubble up the exception
  end
end
```

**Comment by timriley** [comment]
@ttdonovan Thanks. I like the friendliness of `#success?` and `#failure?` (and as a heavy user of `Either` monads myself, I kind of wish we had similar there).

I've been thinking this over some more, and I think perhaps I was too quick to suggest that `Try` returns an `Either` just to avoid the ongoing catching of errors in chained `#bind` or `#fmap` calls. Also, given that `Try` (or `Try`-like things) exist in a few places, like Rust and Scala, I think it probably makes sense for dry-monads to provide a version with similar behaviour. Any user of `Try` who doesn't want this behaviour can always use `#to_either` to break out of the exception catching, anyway.

I'm sorry about the back and forth here. This is super early days for this project and it's taking a little while for it to clarify in my head. The approach that feels most comfortable to me is that it should offer faithful representa

So: my feeling is that it'd be good to roll back to your initial commit here, and keep the `#success?` and `#failure?` methods you've most recently introduced.



Thanks for hearing me out :)

**Comment by timriley** [comment]
@ttdonovan Thanks. I like the friendliness of `#success?` and `#failure?` (and as a heavy user of `Either` monads myself, I kind of wish we had similar there).

I've been thinking this over some more, and I think perhaps I was too quick to suggest that `Try` returns an `Either` just to avoid the ongoing catching of errors in chained `#bind` or `#fmap` calls. Also, given that `Try` (or `Try`-like things) exist in a few places, like Rust and Scala, I think it probably makes sense for dry-monads to provide a version with similar behaviour. Any user of `Try` who doesn't want this behaviour can always use `#to_either` to break out of the exception catching, anyway.

I'm sorry about the back and forth here. This is super early days for this project and it's taking a little while for it to clarify in my head. The approach that feels most comfortable to me is that it should offer faithful Ruby representations of the common monads, and not try to be too opinionated about how they are then used.

So: my feeling is that it'd be good to roll back to your initial commit here, and keep the `#success?` and `#failure?` methods you've most recently introduced.

Thanks for hearing me out :)

**Comment by flash-gordon** [comment]
Interesting. Actually `Try` from my point of view makes sense but it is quite dangerous :) You should use it only when you know for sure that your code can raise an error, you should keep wrapped block as small as possible, and you should catch only certain exceptions, not all (if you can). That's why I think it is better to add support of passing list of exception classes to follow the concerns:
```
DBErrors = [UniqueConstraintViolated, ParentKeyNotFound]
Try(DBErrors) { run_update } ->> (r) { Try(NetTimeout) { make_request } }
```
Also @timriley has excellent point to prevent automatic chaining Try with Either. I see it like this:
```
Try(DBErrors) { run_update }.bind(NetTimeout) { |r| make_request }.to_either.bind { success }
```

**Comment by timriley** [comment]
I wonder if we could allow an exception list to be passed as an optional argument to `Try()`?

**Comment by ttdonovan** [comment]
@timriley I've reverted some of my changes but kept the `#success?` and `#failure?`. I'm open to the idea of passing in an optional list of exceptions but am uncertain exactly what the implementation would look like. If I had to guess it would be something like Rust's `match` in https://doc.rust-lang.org/std/macro.try!.html - if the exception was not defined in the collection is would `raise`. So fare I believe this `Try {}` interface matches closest to Scala http://www.scala-lang.org/api/2.9.3/scala/util/Try.html - with the use of `#success?` and `#failure?`.

**Comment by AMHOL** [comment]
@ttdonovan should be able to do something like:

```ruby
module Dry
  module Monads
    class Try
      attr_reader :exception, :value

      def self.lift(exceptions, f)
        Success.new(f.call)
      rescue *exceptions => e
        Failure.new(e)
      end
    end

    module Mixin
      Try = Try
      
      def Try(*exceptions, &f)
        catchable = exceptions.any? ? exceptions.flatten : [StandardError]
        Try.lift(catchable, f)
      end
  end
end
```

**Comment by ttdonovan** [comment]
@AMHOL thank's I've added an optional catchable exceptions list to `Try {}` and updated the specs.

**Comment by AMHOL** [comment]
@ttdonovan, nice, looks good to me, best to wait and see what @timriley thinks though

**Comment by timriley** [comment]
Thanks everyone! This is looking good to me, @ttdonovan, I reckon it's ready to go. Would you mind setting up a new PR to target `master` (perhaps also squishing down the commits, since we've done a bit of back and forth here)? Then I can merge it in 😄

**Comment by ttdonovan** [comment]
A new pull request has been created #5

**Pull request closed without merging**
