### PR TITLE
Add Result with fixed Failure type

### PR DESCRIPTION
**Pull request by flash-gordon**
This adds a concept of Either with a fixed error type. It is common to have only one successful type of an operation chain with a bunch of unsuccessful outcomes. We can restrict the left part to have only context-dependent types of value. This comes with a few benefits:

1. An explicit listing of error types is good as documentation of the result type.
1. If a user tries to return an unlisted error this will throw an error preventing from a new undocumented error.
1. A variant of Either matcher can be added to dry-matcher to require exhaustive matching on all failing cases.

This is how I see it in code

```ruby
class AcceptPayment
  NetError =
    Types::Instance(TimeoutError) |
    Types::Instance(ConnectionFailed)

  ProcessingError =
    NetError | 
    Types::Instance(Errors::InvalidResponse) |
    Types::Value(:no_user) |
    Types::Value(:no_account)

  include Dry::Monads::Either(ProcessingError)
  include Dry::Matcher::Either(ProcessingError)

  def call(payment_id)
    check_status.bind do |payment| 
      find_user_with_account.bind { |user, acc| accept_payment(payment, user, acc) } } 
    end
  end

  def check_status
    Right(make_net_request)
  rescue NetError, Errors::InvalidResponse => error
    Left(error)
  end

  def find_user_with_account 
    Right([
      get_user || return Left(:no_user), 
      get_account || return Left(:no_account)
    ])
  end
end

AcceptPayment.new.call do |m|
  m.success do 
    # ...
  end
  
  m.failure AcceptPayment::NetError do
    # ...
  end

  m.failure Errors::InvalidResponse do
    # ...
  end

  m.failure :no_user, :no_account do
    # ...
  end
end
```

This doesn't offer anything radically new, just makes error handling a bit better described. We still can't be sure all possible cases are handled because we program in a dynamic language but combined with 100% code coverage this is a good way to write error-prone code in critical places FWIW.

The snippet above uses a syntax I'd like to see in dry-types OOTB. I'll send a corresponding PR to dry-t.

@timriley @solnic what're your thoughts on this?

### CODE REVIEW

**Comment by timriley** [comment]
@flash-gordon I really like this!

**Comment by solnic** [comment]
LGTM

**Comment by citizen428** [comment]
FWIW, I really like this. It's a common [idiom in Rust](https://doc.rust-lang.org/book/first-edition/error-handling.html#the-result-type-alias-idiom):

```ruby
type Result<T> = result::Result<T, ParseIntError>;
```

**Comment by flash-gordon** [comment]
OK, finally gonna merge it and add docs in master

**Comment by flash-gordon** [comment]
Ah, also, I made it work with arbitrary types besides dry-t's objects, e.g.
```ruby
include Dry::Monads::Result(Symbol)

def foo_bar_baz
  Failure(:not_ok) # => fine
  Failure("not_ok") # => raises an error
end
```

**Pull request merged**
