### PR TITLE
Draft of Either & Maybe implementation

### PR DESCRIPTION
**Pull request by flash-gordon**

### CODE REVIEW

**Comment by solnic** [comment]
Could you add a couple of integration tests so that we can see the API in action?

**Comment by flash-gordon** [comment]
Sure, pls give some time :) I'll add some basic stuff later today

**Comment by solnic** [comment]
Sure man, no rush at all, take your time and thank you

**Comment by flash-gordon** [comment]
@solnic @timriley Just pushed some specs for Either monad to illustrate my vision of its interface. I tried not to go far from original kleisli implementation in order to keep backward compatibility. I replaced `#>>` with `#bind` and `#or` with `#alt` (my spacemacs goes wild when I write `end.or do`). Also `#bind` now can take a block that allows to chain calls nicely. That summarizes my experience of using dry-transactions for now. It could a good idea to add ability to enumerate list of possible errors in a chain but I don't know how to that (it is 2 AM here atm :) and perhaps it should be wrapped at some higher level (e.g. in transactions). 

Please take a look. Keep in mind that Maybe implementation is almost identical so I didn't write specs for it.

**Comment by solnic** [comment]
I've got mixed feelings about `or` vs `alt`, the former seems nicer / more obvious

**Comment by flash-gordon** [comment]
I don't mind about exact name, my concern is that using language keywords as methods can lead to strange problems with editors. I can't foresee them now so my suggestion is to change the syntax. On the other hand ruby syntax has examples of mixing keywords with method names such as `class` and I haven't heard about any issues with it. Therefore using `#or` should be safe enough.

**Comment by solnic** [comment]
Lots of gems out there use `.or` method.

**Comment by flash-gordon** [comment]
Possible issue is using `or` in a DSL without `self` keyword (`#instance_exec`) but thankfully it is not the case for monads so I agree with you :)

**Comment by timriley** [comment]
I prefer the `.or` method here too.

**Comment by flash-gordon** [comment]
OK, I replaced `#alt` with `#or`.

**Comment by solnic** [comment]
Cool! I really like that you put this stuff in a mixin, I never liked
globals in kleisli.

**Comment by timriley** [comment]
So this is looking really good. Really like that it's a mixin, and I also like how you've kept the "bind" method simple compared to Kleisli's syntax trickery (which I found actually made it quite difficult to chain operations).

@solnic you happy for this to go into master?

**Comment by ttdonovan** [comment]
Once this merged into master it would get great if someone with the right credentials could setup all the extra services Travis, CodeClimate, Coveralls.

**Comment by timriley** [comment]
Yep, I can help with that.

**Comment by solnic** [comment]
:+1:

**Comment by flash-gordon** [comment]
OK, let's do it

**Comment by timhabermaas** [comment]
@flash-gordon I'm kinda late to the party, but I find `>>` as an alias for `bind` rather unfortunate since `>>` exists in Haskell\* (`>> :: m a -> m b -> m b`) and means bind without caring about the bound value:

```ruby
def >>(other)
  bind do |_|
    other
  end
end
```

\* `fmap` looks like the naming is borrowed from Haskell, so this is rather unintuitive.

**Comment by flash-gordon** [comment]
@timhabermaas thanks for your feedback, it's never too late :) `>>` is a backport from kleisli gem and I don't like it personally because ruby does not play nice with it. At least I tried to replace most of examples and specs with `bind`. Also keep in mind that ruby is dynamically typed language so there is no real difference between `>>` and `>>=` here (and the last is not available in the language). And I thought about `fmap` that can be replaced with `map` but I don't want to confuse people because of `Enumerable#map` though we can introduce some other name if you suggest one.

**Comment by timriley** [comment]
I'm in favour of removing the symbolic operators and sticking to descriptive names that align as closely as possible to established monad behaviours in other languages.

So, let's start by removing `>>`. And then we can have another conversation about `map` vs `fmap` :)

**Comment by solnic** [comment]
Big :-1: for using `map` because of `Enumerable#map`. And :+1: for removing `>>` esp that it's our pipeline operator in rom and dry-pipeline and transproc.

**Comment by flash-gordon** [comment]
@ttdonovan do you have any pros for `>>` besides backward compatibility?

**Comment by ttdonovan** [comment]
I have no objections if `>>` was removed. Only alternative I could think of
as an option for `>>=` would be something like `>>>` but not sure if that
implies another meaning in other languages.

**Comment by flash-gordon** [comment]
Fine. I removed `>>`.

**Pull request merged**
