### PR TITLE
fix fail M.Right(nil).to_maybe

### PR DESCRIPTION
**Pull request by borisaka**
https://github.com/dry-rb/dry-monads/issues/25

### CODE REVIEW

**Comment by flash-gordon** [comment]
Hey @borisaka 
This is a bit strange to have Right value with nil value inside. Just a bit. The much more strange thing is that `Maybe(nil)` returns `None` to you, which means `Right(nil)` becomes `None`. Well, quite unexpectedly tbf. I think we need to issue a warning (by calling `Kernel#warn`) in this case so people won't get an error but probably will be notified about an unexpected transformation. Also we definitely need specs for it. Do you want to give it a try?

**Comment by borisaka** [comment]
this way?
```ruby
def to_maybe
  Kernel.warn('Unexpected transformation: Right(nil) will transform to None')
  Dry::Monads::Maybe(value)
end		      
```
I can try to do it on next weekend

**Comment by flash-gordon** [comment]
@borisaka yes, but only for nil values `warn 'Right(nil) transformed to None' if value.nil?`

**Comment by borisaka** [comment]
obviously yes=)

**Comment by borisaka** [comment]
@flash-gordon, I updated pull request.  Have I to squash my 2 commits, or fix something else?

**Comment by flash-gordon** [comment]
hey, sorry for delay, no worries, it's fine, I've merged this in, check out master branch

**Pull request closed without merging**
